name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

jobs:

  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      # - name: Typing
      #   run: mypy --ignore-missing-imports mouracx
      - name: Look for style errors
        run: pflake8
      - name: Check for importing style
        run: isort --profile=black --check --diff mouracx tests integration
      - name: Look for auto format errors
        run: black --check --diff mouracx tests integration


  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run tests
        run: pytest -v --cov=mouracx --junitxml=test-result.xml
